name: Build

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    uses: ./.github/workflows/sub_tests.yml
      
  build_binaries:
    needs: [tests]
    uses: ./.github/workflows/sub_build_binaries.yml
    with:
      upload_release_assets: ${{ github.event_name == 'release' }}

  build_docker:
    needs: [tests]
    uses: ./.github/workflows/sub_build_docker.yml
    with:
      push_hub: ${{ github.event_name == 'release' || github.ref == 'refs/heads/main' }}
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
